### ISSUE TITLE
Améliorations

### ISSUE THREAD

**Issue by guifucy** [jaunefra/MineralContest#2]
Salut,
Merci pour ce plugin,
Petite question, quand est prévu la modification pour ajouter des maps customs ?
D'autres pars ça pourrait être cool de pouvoir choisir le nombre d'équipe pour les maps customs
Merci ;)

**Comment by jaunefra** [comment]
Je bosse petit à petit sur la création de map custom, mes cours en priorité ! Mais elle devrait sortir dans pas trop longtemps, je l'espère.
C'est une bonne idée, je vais noter ça

**Comment by guifucy** [comment]
je n'arrive pas à faire fonctionner le plugin avec les maps sur mon serveur, as tu un discord sur lequel je peux te parler pour éviter de spam les issues ?

**Comment by jaunefra** [comment]
La version avec les map à construire n'est pas terminée, elle n'est donc pas encore fonctionnelle.
Je viens de créer un discord, https://discord.gg/VFuUKVC
