### ISSUE TITLE
L'étape 1 est cassée

### ISSUE THREAD

**Issue by pjoulot** [jaunefra/MineralContest#3]
L'étape 1: **Télécharger la map http://mineral.synchroneyes.fr/**

Le lien http://mineral.synchroneyes.fr/download/map/world.zip retourne une erreur 500.

Serait-il possible de committer la map ou d'actualiser les étapes?

**Comment by jaunefra** [comment]
Yes ! C'est vrai. J'ai changé le système de téléchargement vendredi soir et j'ai oublié d'update le readme.

http://synchroneyes.fr/downloads/
